server:
  port: 8002

spring:
  application:
    name: helloServer

hello:
  message: Hello local configuration
  name: hello-server-2

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: HelloService-8002
    prefer-ip-address: true     #访问路径可以显示IP地址